version: "3.6"

volumes:
  redis_db:
    driver: local
  node_modules:
    driver: local

services:
  reader:
    build:
      context: .
    command: node reader/index.js
    restart: always
    devices:
      - "/dev/ttyUSB0"
    environment:
      REDIS_HOST: redis://redis
      MQTT_BROKER_HOST: broker
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  broker:
    build:
      context: .
    command: node broker/index.js
    restart: always
    ports:
      - "1883:1883"
    environment:
      REDIS_HOST: redis

  # server:
  #   build:
  #     context: .
  #   command: node server/index.js
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   environment:
  #     - REDIS_HOST=redis://redis
  #   volumes:
  #     - node_modules:/usr/src/app/node_modules
  #     - ./:/usr/src/app

  # server-test:
  #   build:
  #     context: .
  #   command: npm test
  #   environment:
  #     - REDIS_HOST=redis://redis
  #   volumes:
  #     - node_modules:/usr/src/app/node_modules
  #     - ./:/usr/src/app

  redis:
    image: redis
    volumes:
      - redis_db:/data
