version: "3.6"

volumes:
  redis_db:
    driver: local
  node_modules:
    driver: local

services:
  reader:
    build:
      context: .
    command: node reader/index.js
    restart: always
    devices:
      - "/dev/ttyUSB0"
    environment:
      REDIS_HOST: redis://redis
      MQTT_BROKER_HOST: mqtt://broker
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  broker:
    build:
      context: .
    command: node broker/index.js
    restart: always
    ports:
      - "1883:1883"
    environment:
      REDIS_HOST: redis
      KOA_HOST: http://koa
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  koa:
    build:
      context: .
    command: node koa/index.js
    ports:
      - "80:3000"
    restart: always
    environment:
      REDIS_HOST: redis://redis
      MQTT_BROKER_HOST: mqtt://easymeter.local
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  # koa-test:
  #   build:
  #     context: .
  #   command: npm test
  #   environment:
  #     REDIS_HOST: redis://redis
  #   volumes:
  #     - node_modules:/usr/src/app/node_modules
  #     - ./:/usr/src/app

  redis:
    image: redis
    volumes:
      - redis_db:/data
