version: "3.6"

volumes:
  redis_db:
    driver: local
  node_modules:
    driver: local

services:
  reader:
    build:
      context: .
    command: node reader/index.js
    restart: always
    devices:
      - "/dev/ttyUSB0"
    environment:
      - REDIS_HOST=redis://redis
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  server:
    build:
      context: .
    #command: node_modules/.bin/nodemon --exec node server/index.js
    ports:
      - "80:3000"
    restart: always
    environment:
      - REDIS_HOST=redis://redis
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  redis:
    image: redis
    volumes:
      - redis_db:/data
