version: "3.6"

volumes:
  node_modules:
    driver: local

services:
  reader:
    build:
      context: .
    command: node reader/index.js
    devices:
      - "/dev/ttyUSB0"
    volumes:
      - node_modules:/usr/src/app/node_modules

  koa:
    build:
      context: .
    command: node koa/index.js
    ports:
      - "80:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
