version: "3.6"

volumes:
  node_modules:
    driver: local

services:
  reader:
    build:
      context: .
    command: node reader/index.js
    restart: always
    devices:
      - "/dev/ttyUSB0"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  koa:
    build:
      context: .
    command: node koa/index.js
    ports:
      - "80:3000"
    restart: always
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app
  # koa-test:
  #   build:
  #     context: .
  #   command: npm test
  #   environment:
  #     REDIS_HOST: redis://redis
  #   volumes:
  #     - node_modules:/usr/src/app/node_modules
  #     - ./:/usr/src/app
